import math

from gittins_reference.detmath import exp2


class TestExactValues:
    def test_integer_powers_are_exact(self):
        assert exp2(0.0) == 1.0
        assert exp2(1.0) == 2.0
        assert exp2(10.0) == 1024.0
        assert exp2(-1.0) == 0.5
        assert exp2(-10.0) == 0.0009765625

    def test_clamps(self):
        assert exp2(1024.0) == math.inf
        assert exp2(5000.0) == math.inf
        assert exp2(-1075.0) == 0.0
        assert exp2(-1e9) == 0.0
        assert math.isnan(exp2(math.nan))


class TestPinnedVectors:
    # Golden vectors: any other implementation must match these bit for bit.
    # (Values generated by this reference implementation; see spec/decay.md.)
    def test_fractional_powers(self):
        assert exp2(0.5) == 1.414213562373095
        assert exp2(-0.5) == 0.7071067811865475
        assert exp2(1.75) == 3.363585661014858
        assert exp2(-100.25) == 6.633503073341491e-31


class TestAccuracy:
    def test_close_to_platform_exp2(self):
        # Sanity, not spec: within a few ulp of the platform's exp2.
        for i in range(10_000):
            x = -50.0 + i * 0.01
            ours, theirs = exp2(x), math.exp2(x)
            assert abs(ours - theirs) <= 4 * math.ulp(theirs)

    def test_monotone_on_a_grid(self):
        prev = exp2(-8.0)
        for i in range(1, 4_000):
            cur = exp2(-8.0 + i * 0.004)
            assert cur >= prev
            prev = cur
